import Head from "next/head";
import MarkdownEditor from "C-Markdown/index";
import Button from "@/components/Common/Button";

export default function Home() {
  const onClickButton = (key: string) => {
    console.log(`key: ${key}`);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MarkdownEditor />
        <Button
          onClick={() => onClickButton("main")}
          svg={"follow"}
          type="main"
        >
          hello1
        </Button>
        <Button onClick={() => onClickButton("black")} type="black">
          hello2
        </Button>
        <Button onClick={() => onClickButton("white")} type="white">
          hello3
        </Button>
        <Button onClick={() => onClickButton("")} type="">
          hello3
        </Button>
      </main>
    </>
  );
}
