import Head from "next/head";
import MarkdownEditor from "@/components/Organisms/MarkDownEditor/index";
import Button from "@/components/Atoms/Button";
import Header from "@/components/Organisms/Header";
import { ButtonClass } from "@/components/Atoms/Button/types";

export default function Home() {
  const onClickButton = (key: string) => {
    console.log(`key: ${key}`);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header></Header>
        <MarkdownEditor />
        <Button
          onClick={() => onClickButton("main")}
          svg={"follow"}
          buttonClass={new ButtonClass("round", "blue", "white", false, 28, 14)}
        >
          hello1
        </Button>
      </main>
    </>
  );
}
